steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/ford-perfect', '--tag=eu.gcr.io/$PROJECT_ID/ford-perfect:$SHORT_SHA', '.']
  dir: ford-perfect
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['--namespace', '${_NAMESPACE}', 'apply', '-f', '.']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  dir: ford-perfect
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['--namespace', '${_NAMESPACE}', 'set', 'image', 'deployment/ford-perfect-deployment', 'ford-perfect-app=eu.gcr.io/$PROJECT_ID/ford-perfect:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
images: ['eu.gcr.io/$PROJECT_ID/ford-perfect']
tags: ['$SHORT_SHA']
substitutions:
  _COMPUTE_ZONE: europe-west3-b
  _CONTAINER_CLUSTER: ford-perfect-cluster
  _NAMESPACE: default
