type: google.api.Service
config_version: 3

# Name of the service configuration.
name: telegrambotapi.endpoints.hacker-playground.cloud.goog

# API title to appear in the user interface (Google Cloud Console)
title: Telegram Bot API
apis:
- name: telegrambotapi.TelegramBotApi

# API usage restrictions.
usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true