// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telegram_bot_api.proto

package telegrambotapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Updates struct {
	Ok                   bool      `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Result               []*Update `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Updates) Reset()         { *m = Updates{} }
func (m *Updates) String() string { return proto.CompactTextString(m) }
func (*Updates) ProtoMessage()    {}
func (*Updates) Descriptor() ([]byte, []int) {
	return fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd, []int{0}
}
func (m *Updates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Updates.Unmarshal(m, b)
}
func (m *Updates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Updates.Marshal(b, m, deterministic)
}
func (dst *Updates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Updates.Merge(dst, src)
}
func (m *Updates) XXX_Size() int {
	return xxx_messageInfo_Updates.Size(m)
}
func (m *Updates) XXX_DiscardUnknown() {
	xxx_messageInfo_Updates.DiscardUnknown(m)
}

var xxx_messageInfo_Updates proto.InternalMessageInfo

func (m *Updates) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Updates) GetResult() []*Update {
	if m != nil {
		return m.Result
	}
	return nil
}

type Update struct {
	UpdateId             int32    `protobuf:"varint,1,opt,name=update_id,json=updateId" json:"update_id,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd, []int{1}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetUpdateId() int32 {
	if m != nil {
		return m.UpdateId
	}
	return 0
}

func (m *Update) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Message struct {
	MessageId            int32    `protobuf:"varint,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	From                 *User    `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Chat                 *Chat    `protobuf:"bytes,3,opt,name=chat" json:"chat,omitempty"`
	Date                 int32    `protobuf:"varint,4,opt,name=date" json:"date,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Message) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetChat() *Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *Message) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	IsBot                bool     `protobuf:"varint,2,opt,name=is_bot,json=isBot" json:"is_bot,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Chat struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd, []int{4}
}
func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (dst *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(dst, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chat) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Chat) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*Updates)(nil), "telegrambotapi.Updates")
	proto.RegisterType((*Update)(nil), "telegrambotapi.Update")
	proto.RegisterType((*Message)(nil), "telegrambotapi.Message")
	proto.RegisterType((*User)(nil), "telegrambotapi.User")
	proto.RegisterType((*Chat)(nil), "telegrambotapi.Chat")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TelegramBotApiClient is the client API for TelegramBotApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TelegramBotApiClient interface {
	ReceiveUpdates(ctx context.Context, in *Update, opts ...grpc.CallOption) (*empty.Empty, error)
}

type telegramBotApiClient struct {
	cc *grpc.ClientConn
}

func NewTelegramBotApiClient(cc *grpc.ClientConn) TelegramBotApiClient {
	return &telegramBotApiClient{cc}
}

func (c *telegramBotApiClient) ReceiveUpdates(ctx context.Context, in *Update, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/telegrambotapi.TelegramBotApi/ReceiveUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramBotApiServer is the server API for TelegramBotApi service.
type TelegramBotApiServer interface {
	ReceiveUpdates(context.Context, *Update) (*empty.Empty, error)
}

func RegisterTelegramBotApiServer(s *grpc.Server, srv TelegramBotApiServer) {
	s.RegisterService(&_TelegramBotApi_serviceDesc, srv)
}

func _TelegramBotApi_ReceiveUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramBotApiServer).ReceiveUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telegrambotapi.TelegramBotApi/ReceiveUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramBotApiServer).ReceiveUpdates(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelegramBotApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "telegrambotapi.TelegramBotApi",
	HandlerType: (*TelegramBotApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveUpdates",
			Handler:    _TelegramBotApi_ReceiveUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telegram_bot_api.proto",
}

func init() {
	proto.RegisterFile("telegram_bot_api.proto", fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd)
}

var fileDescriptor_telegram_bot_api_4b8f07bfd4ba6edd = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0x32, 0x69, 0x9b, 0xfc, 0x41, 0x59, 0x58, 0x43, 0x89, 0x3a, 0x20, 0x55, 0x59, 0x65,
	0x95, 0x8a, 0x72, 0x02, 0x06, 0x21, 0xd1, 0x05, 0x2c, 0x2c, 0x40, 0xec, 0x2a, 0x77, 0xe2, 0xb6,
	0x56, 0x93, 0xd8, 0x8a, 0x7f, 0x10, 0xb3, 0x45, 0xe2, 0x04, 0x5c, 0x81, 0x1b, 0x71, 0x05, 0x0e,
	0x82, 0xfc, 0x9d, 0x0c, 0x9a, 0x19, 0x66, 0xf7, 0xfd, 0xde, 0xcb, 0x7f, 0xcf, 0xce, 0x83, 0x39,
	0xca, 0x5a, 0x1e, 0x3a, 0xd1, 0x6c, 0x77, 0x1a, 0xb7, 0xc2, 0xa8, 0xd2, 0x74, 0x1a, 0x35, 0x4b,
	0x47, 0x7c, 0xa7, 0x51, 0x18, 0xb5, 0x78, 0x7e, 0xd0, 0xfa, 0x50, 0xcb, 0x95, 0x30, 0x6a, 0x25,
	0xda, 0x56, 0xa3, 0x40, 0xa5, 0x5b, 0xeb, 0xd5, 0x8b, 0xcb, 0x81, 0xa5, 0xd3, 0xae, 0xdf, 0xaf,
	0x64, 0x63, 0xf0, 0xc6, 0x93, 0xf9, 0x06, 0x66, 0x9f, 0x4c, 0x25, 0x50, 0x5a, 0x96, 0x42, 0xa8,
	0x4f, 0x59, 0xb0, 0x0c, 0x8a, 0x98, 0x87, 0xfa, 0xc4, 0x4a, 0x98, 0x76, 0xd2, 0xf6, 0x35, 0x66,
	0xe1, 0xf2, 0xac, 0x38, 0x5f, 0xcf, 0xcb, 0xbb, 0xb6, 0xa5, 0xff, 0x90, 0x0f, 0xaa, 0xfc, 0x0b,
	0x4c, 0x3d, 0xc2, 0x2e, 0x21, 0xe9, 0x69, 0xda, 0xaa, 0x8a, 0x16, 0x4e, 0x78, 0xec, 0x81, 0x4d,
	0xc5, 0x5e, 0xc2, 0xac, 0x91, 0xd6, 0x8a, 0x83, 0xcc, 0xc2, 0x65, 0x50, 0x9c, 0xaf, 0x9f, 0xdd,
	0xdf, 0xfb, 0xde, 0xd3, 0x7c, 0xd4, 0xe5, 0xbf, 0x02, 0x98, 0x0d, 0x20, 0x7b, 0x01, 0x30, 0xc0,
	0xff, 0x96, 0x27, 0x03, 0xb2, 0xa9, 0x58, 0x01, 0xd1, 0xbe, 0xd3, 0xcd, 0xb0, 0xfa, 0xe2, 0x41,
	0x64, 0x2b, 0x3b, 0x4e, 0x0a, 0xa7, 0xbc, 0x3e, 0x0a, 0xcc, 0xce, 0xfe, 0xaf, 0x7c, 0x73, 0x14,
	0xc8, 0x49, 0xc1, 0x18, 0x44, 0x2e, 0x7b, 0x16, 0x91, 0x19, 0xcd, 0x0e, 0x43, 0xf9, 0x0d, 0xb3,
	0xc9, 0x32, 0x28, 0x12, 0x4e, 0x73, 0xfe, 0x23, 0x80, 0xc8, 0x19, 0xb8, 0x97, 0xbc, 0xcd, 0x16,
	0xaa, 0x8a, 0x3d, 0x85, 0xa9, 0xb2, 0xee, 0x1f, 0x52, 0xac, 0x98, 0x4f, 0x94, 0xbd, 0xd2, 0xe8,
	0xae, 0xb2, 0x57, 0x9d, 0xc5, 0x6d, 0x2b, 0x1a, 0x49, 0x39, 0x12, 0x9e, 0x10, 0xf2, 0x41, 0x34,
	0xf4, 0x8a, 0xb5, 0x18, 0xd9, 0x88, 0xd8, 0xd8, 0x01, 0x44, 0x2e, 0x20, 0xee, 0xad, 0xec, 0x88,
	0xf3, 0x19, 0x6e, 0xcf, 0xf9, 0x06, 0x22, 0x97, 0xfe, 0x41, 0x8c, 0xbb, 0x7e, 0xe1, 0x7d, 0x3f,
	0x77, 0xa5, 0x1b, 0x33, 0x06, 0xa1, 0x79, 0x7d, 0x84, 0xf4, 0xe3, 0xf0, 0x2e, 0x57, 0x1a, 0x5f,
	0x1b, 0xc5, 0x3e, 0x43, 0xca, 0xe5, 0xb5, 0x54, 0x5f, 0xe5, 0xd8, 0x9b, 0x47, 0x7a, 0xb1, 0x98,
	0x97, 0xbe, 0x78, 0xe5, 0x58, 0xbc, 0xf2, 0xad, 0x2b, 0x5e, 0x7e, 0xf1, 0xfd, 0xf7, 0x9f, 0x9f,
	0x61, 0x9a, 0x3f, 0x59, 0xf9, 0x4e, 0xd8, 0x77, 0x5a, 0x9f, 0x76, 0x53, 0x52, 0xbd, 0xfa, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0xa5, 0x06, 0x71, 0xf4, 0x02, 0x00, 0x00,
}
