apiVersion: v1
kind: Service
metadata:
  name: ford-perfect-service
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: ford-perfect-app
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ford-perfect-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ford-perfect-app
    spec:
      containers:
      - name: ford-perfect-app
        image: eu.gcr.io/hacker-playground/ford-perfect
        ports:
        - name: https-port
          containerPort: 8443
        env:
        - name: TELEGRAM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-api-credentials
              key: token
        readinessProbe:
          httpGet:
            path: /ready
            port: https-port
            scheme: HTTPS
        livenessProbe:
          httpGet:
            path: /healthz
            port: https-port
            scheme: HTTPS
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: nginx-ssl
            readOnly: true
      volumes:
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
