apiVersion: v1
kind: Service
metadata:
  name: ford-perfect-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ford-perfect-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ford-perfect-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ford-perfect-app
    spec:
      containers:
      - name: ford-perfect-app
        image: eu.gcr.io/hacker-playground/ford-perfect
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: http-port
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
